services:
  app:
    image: ${IMAGE:-jellyfin-refresh:latest}
    container_name: jellyfin-refresh
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount media folders and symlinks
      - /mnt:/mnt
      - /media:/media
      # Mount config and data folders
      - /data:/opt/docker/jellyfin-refresh/data
